import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainContentLayout({
  children,
  cartModal
}: Readonly<{
  children: React.ReactNode;
  cartModal: React.ReactNode
}>) {
  return (
    <div className="w-[100%]">
        <Header />
        <main>
          {cartModal}
          {children}
        </main>
        {/* <div>Footer</div> */}
    </div>
  );
}
